carpentry: incubator
title: Programming with GAP
created: '2014-10-21'
keywords: software, data, lesson, The Carpentries
life_cycle: stable
license: CC-BY 4.0
source: https://github.com/carpentries-incubator/gap-lesson
branch: main
contact: obk1@st-andrews.ac.uk
episodes:
- 01-command-line.md
- 02-some-objects.md
- 03-func.md
- 04-testing.md
- 05-small-groups.md
- 06-attributes.md
learners: ~
instructors: ~
profiles: ~
carpentry_description: Lesson Description
lang: uk
